const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const database = JSON.parse(
  fs.readFileSync(path.join(root, "data", "hexagrams_db.json"), "utf8")
);
const metadata = JSON.parse(
  fs.readFileSync(path.join(root, "data", "hexagrams_db.meta.json"), "utf8")
);

const records = Object.entries(database)
  .map(([code, record]) => ({
    code,
    number: record.king_wen_number,
    displayNumber: String(record.king_wen_number).padStart(2, "0"),
    symbol: record.symbol,
    name: record.name,
    canonicalName: record.canonical_name,
    upperTrigram: record.upper_trigram,
    lowerTrigram: record.lower_trigram,
    judgement: record.judgement,
    tuan: record.tuan,
    image: record.image,
    lines: Object.entries(record.lines)
      .sort(([left], [right]) => Number(left) - Number(right))
      .map(([position, line]) => ({
        position: Number(position),
        lineName: line.line_name,
        yinYang: line.yin_yang,
        glyph: line.yin_yang === "阳" ? "━━━━━━" : "━━  ━━",
        text: line.text,
        image: line.image
      })),
    specialLine: record.special_line
      ? {
          lineName: record.special_line.line_name,
          text: record.special_line.text,
          image: record.special_line.image
        }
      : null,
    sourceTitle: record.source.title,
    sourceUrl: record.source.url,
    verificationUrl: record.source.verification_url,
    keywords: [
      record.name,
      record.canonical_name,
      record.upper_trigram,
      record.lower_trigram,
      String(record.king_wen_number)
    ].join(" ")
  }))
  .sort((left, right) => left.number - right.number);

if (records.length !== 64) {
  throw new Error(`Expected 64 records, received ${records.length}`);
}

const output = `// Generated by scripts/build_miniprogram_culture_data.js. Do not edit manually.\n` +
  `const HEXAGRAMS = ${JSON.stringify(records, null, 2)};\n\n` +
  `module.exports = {\n` +
  `  DATABASE_SHA256: ${JSON.stringify(metadata.sha256)},\n` +
  `  HEXAGRAMS\n` +
  `};\n`;

const destination = path.join(
  root,
  "miniprogram-culture",
  "data",
  "hexagrams.js"
);
fs.mkdirSync(path.dirname(destination), { recursive: true });
fs.writeFileSync(destination, output, "utf8");
console.log(`Wrote ${records.length} records to ${destination}`);
